apiVersion: v1
kind: Secret
metadata:
  name: postgres-deployment-secret
  labels:
    name: postgres-user-service
    app: capitec-user-service
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: capitec_user_service
  POSTGRES_PORT: "5432"
