apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  labels:
    name: postgres-db-service
    app: capitec-user-service
spec:
  selector:
    name: postgres-user-service
    app: capitec-user-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30002
  type: NodePort